administrator/urls.py
from django.urls import path

from administrator.views import (
    create_academic_session_view,
    create_assign_view,
    create_class_view,
    create_course_view,
    create_department_view,
    create_subject_view,
    create_time_slot_view,
    delete_academic_session_view,
    delete_assign_view,
    delete_class_view,
    delete_course_view,
    delete_department_view,
    delete_subject_view,
    delete_time_slot_view,
    detail_academic_session_view,
    detail_assign_view,
    detail_class_view,
    detail_course_view,
    detail_department_view,
    detail_subject_view,
    detail_time_slot_view,
    home_view,
    list_academic_session_view,
    list_assign_view,
    list_class_view,
    list_course_view,
    list_department_view,
    list_subject_view,
    list_time_slot_view,
    update_academic_session_view,
    update_assign_view,
    update_class_view,
    update_course_view,
    update_department_view,
    update_subject_view,
    update_time_slot_view,
)
from administrator.views_staff import (
    create_staff_view,
    delete_staff_view,
    detail_staff_view,
    list_staff_view,
    password_change_view,
    profile_update_view,
    profile_view,
    update_staff_view,
)
from administrator.views_student import (
    create_student_view,
    delete_student_view,
    detail_student_view,
    list_student_view,
    update_student_view,
)

app_name = "administrator"

urlpatterns = [
    path("", home_view, name="home"),
    path("academic_session_add/", create_academic_session_view, name="academic-session-add"),
    path("academic_session_list/", list_academic_session_view, name="academic-session-list"),
    path("academic_session_detail/<uuid>/", detail_academic_session_view, name="academic-session-detail"),
    path("academic_session_update/<uuid>/", update_academic_session_view, name="academic-session-update"),
    path("academic_session_delete/<uuid>/", delete_academic_session_view, name="academic-session-delete"),
    path("department_add/", create_department_view, name="department-add"),
    path("department_list/", list_department_view, name="department-list"),
    path("department_detail/<uuid>/", detail_department_view, name="department-detail"),
    path("department_update/<uuid>/", update_department_view, name="department-update"),
    path("department_delete/<uuid>/", delete_department_view, name="department-delete"),
    path("course_add/", create_course_view, name="course-add"),
    path("course_list/", list_course_view, name="course-list"),
    path("course_detail/<uuid>/", detail_course_view, name="course-detail"),
    path("course_update/<uuid>/", update_course_view, name="course-update"),
    path("course_delete/<uuid>/", delete_course_view, name="course-delete"),
    path("class_add/", create_class_view, name="class-add"),
    path("class_list/", list_class_view, name="class-list"),
    path("class_detail/<uuid>/", detail_class_view, name="class-detail"),
    path("class_update/<uuid>/", update_class_view, name="class-update"),
    path("class_delete/<uuid>/", delete_class_view, name="class-delete"),
    path("subject_add/", create_subject_view, name="subject-add"),
    path("subject_list/", list_subject_view, name="subject-list"),
    path("subject_detail/<uuid>/", detail_subject_view, name="subject-detail"),
    path("subject_update/<uuid>/", update_subject_view, name="subject-update"),
    path("subject_delete/<uuid>/", delete_subject_view, name="subject-delete"),
    path("time_slot_add/", create_time_slot_view, name="time-slot-add"),
    path("time_slot_list/", list_time_slot_view, name="time-slot-list"),
    path("time_slot_detail/<uuid>/", detail_time_slot_view, name="time-slot-detail"),
    path("time_slot_update/<uuid>/", update_time_slot_view, name="time-slot-update"),
    path("time_slot_delete/<uuid>/", delete_time_slot_view, name="time-slot-delete"),
    path("assign_add/", create_assign_view, name="assign-add"),
    path("assign_list/", list_assign_view, name="assign-list"),
    path("assign_detail/<uuid>/", detail_assign_view, name="assign-detail"),
    path("assign_update/<uuid>/", update_assign_view, name="assign-update"),
    path("assign_delete/<uuid>/", delete_assign_view, name="assign-delete"),
    # Student Views
    path("student_add/", create_student_view, name="student-add"),
    path("student_list/", list_student_view, name="student-list"),
    path("student_detail/<uuid>/", detail_student_view, name="student-detail"),
    path("student_update/<uuid>/", update_student_view, name="student-update"),
    path("student_delete/<uuid>/", delete_student_view, name="student-delete"),
    # Staff Views
    path("staff_add/", create_staff_view, name="staff-add"),
    path("staff_list/", list_staff_view, name="staff-list"),
    path("staff_detail/<uuid>/", detail_staff_view, name="staff-detail"),
    path("staff_update/<uuid>/", update_staff_view, name="staff-update"),
    path("staff_delete/<uuid>/", delete_staff_view, name="staff-delete"),
    # Profile Views
    path("profile/", profile_view, name="profile"),
    path("profile_update/", profile_update_view, name="profile-update"),
    path("password_change/", password_change_view, name="password-change"),
]

base/urls.py
from django.urls import path

from base.views import (
    email_verify_view,
    home_view,
    login_view,
    logout_view,
    password_change_view,
    password_reset_request_view,
    password_reset_view,
    register_view,
    user_deactivate_view,
    user_delete_view,
    user_profile_view,
    user_update_view,
)

app_name = "base"

urlpatterns = [
    path("", home_view, name="home"),
    path("register/", register_view, name="user-register"),
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("user_profile/", user_profile_view, name="user-profile"),
    path("user_profile/<str:user_id>", user_profile_view, name="user-profile"),
    path("user_update/", user_update_view, name="user-update"),
    path("email_verification/<uidb64>/<token>/", email_verify_view, name="email-verify"),
    path("password_change/", password_change_view, name="password-change"),
    path("password_reset_request/", password_reset_request_view, name="password-reset-request"),
    path("password_reset/<uidb64>/<token>/", password_reset_view, name="password-reset"),
    path("user_deactivate/", user_deactivate_view, name="user-deactivate"),
    path("user_delete/", user_delete_view, name="user-delete"),
]

school/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("base/", include("base.urls", namespace="base")),
    path("administrator/", include("administrator.urls", namespace="administrator")),
    path("accountant/", include("accountant.urls", namespace="accountant")),
    path("staff/", include("staff.urls", namespace="staff")),
    path("student/", include("student.urls", namespace="student")),
    path("conference/", include("conference.urls", namespace="conference")),
    path("", include("website.urls", namespace="website")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "base.views.page_not_found_view"

administrator/views.py
from django.contrib import messages
from django.shortcuts import redirect, render

from accountant.forms import FeeForm
from accountant.models import Fee
from administrator.decorators import administrator_message, administrator_required
from administrator.forms import (
    AcademicSessionForm,
    AssignForm,
    ClassForm,
    CourseForm,
    DepartmentForm,
    SubjectForm,
    TimeSlotForm,
)
from administrator.models import (
    AcademicSession,
    Assign,
    Class,
    Course,
    Department,
    Subject,
    TimeSlot,
)


def get_adademic_session(uuid):
    try:
        academic_session = AcademicSession.objects.get(id=uuid)
        return academic_session
    except AcademicSession.DoesNotExist:
        return None


def get_department(uuid):
    try:
        department = Department.objects.get(id=uuid)
        return department
    except Department.DoesNotExist:
        return None


def get_course(uuid):
    try:
        course = Course.objects.get(id=uuid)
        return course
    except Course.DoesNotExist:
        return None


def get_class(uuid):
    try:
        current_class = Class.objects.get(id=uuid)
        return current_class
    except Class.DoesNotExist:
        return None


def get_subject(uuid):
    try:
        subject = Subject.objects.get(id=uuid)
        return subject
    except Subject.DoesNotExist:
        return None


def get_time_slot(uuid):
    try:
        time_slot = TimeSlot.objects.get(id=uuid)
        return time_slot
    except TimeSlot.DoesNotExist:
        return None


def get_assign(uuid):
    try:
        assign = Assign.objects.get(id=uuid)
        return assign
    except Assign.DoesNotExist:
        return None


def get_fee(uuid):
    try:
        fee = Fee.objects.get(id=uuid)
        return fee
    except Fee.DoesNotExist:
        return None


@administrator_message
@administrator_required
def home_view(request, *args, **kwargs):
    context = {}
    return render(request, "administrator/home.html", context)


@administrator_message
@administrator_required
def create_academic_session_view(request, *args, **kwargs):
    context = {}
    form = AcademicSessionForm(request.POST or None)

    if request.method == "POST":
        if form.is_valid():
            form.save()
            messages.success(request, f"Academic Session created.")
            return redirect("administrator:academic-session-list")
        else:
            form = form
            messages.error(request, "Error.")

    context["form"] = form
    context["action"] = "Create"
    return render(request, "administrator/academic_session/academic_session_form.html", context)


@administrator_message
@administrator_required
def list_academic_session_view(request, *args, **kwargs):
    context = {}
    academic_sessions = AcademicSession.objects.all()
    context["academic_sessions"] = academic_sessions
    return render(request, "administrator/academic_session/academic_session_list.html", context)


@administrator_message
@administrator_required
def detail_academic_session_view(request, uuid, *args, **kwargs):
    context = {}
    academic_session = get_adademic_session(uuid)
    context["academic_session"] = academic_session
    return render(request, "administrator/academic_session/academic_session_detail.html", context)


@administrator_message
@administrator_required
def update_academic_session_view(request, uuid, *args, **kwargs):
    context = {}

    academic_session = get_adademic_session(uuid)
    form = AcademicSessionForm(request.POST or None, instance=academic_session)

    if request.method == "POST":
        if form.is_valid():
            form.save()
            messages.success(request, f"Academic Session Updated.")
            return redirect("administrator:academic-session-list")
        else:
            form = form
            messages.error(request, "Error.")

    context["form"] = form
    context["action"] = "Update"
    return render(request, "administrator/academic_session/academic_session_form.html", context)


@administrator_message
@administrator_required
def delete_academic_session_view(request, uuid, *args, **kwargs):
    academic_session = get_adademic_session(uuid)

    if request.method == "POST":
        academic_session.delete()
        messages.success(request, f"Academic session has been deleted successfully.")
    else:
        messages.error(request, "Something went wrong.")
    return redirect("administrator:academic-session-list")


@administrator_message
@administrator_required
def create_department_view(request, *args, **kwargs):
    context = {}
    form = DepartmentForm(request.POST or None)

    if request.method == "POST":
        if form.is_valid():
            form.save()
            messages.success(request, f"Department created.")
            return redirect("administrator:department-list")
        else:
            form = form
            messages.error(request, "Error.")

    context["form"] = form
    context["action"] = "Create"
    return render(request, "administrator/department/department_form.html", context)


@administrator_message
@administrator_required
def list_department_view(request, *args, **kwargs):
    context = {}
    departments = Department.objects.all()
    context["departments"] = departments
    return render(request, "administrator/department/department_list.html", context)


@administrator_message
@administrator_required
def detail_department_view(request, uuid, *args, **kwargs):
    context = {}
    department = get_department(uuid)
    context["department"] = department
    return render(request, "administrator/department/department_detail.html", context)


@administrator_message
@administrator_required
def update_department_view(request, uuid, *args, **kwargs):
    context = {}
    department = get_department(uuid)
    form = DepartmentForm(request.POST or None, instance=department)

    if request.method == "POST":
        if form.is_valid():
            form.save()
            messages.success(request, f"Department Updated.")
            return redirect("administrator:department-list")
        else:
            form = form
            messages.error(request, "Error.")

    context["form"] = form
    context["action"] = "Update"
    return render(request, "administrator/department/department_form.html", context)


@administrator_message
@administrator_required
def delete_department_view(request, uuid, *args, **kwargs):
    department = get_department(uuid)

    if request.method == "POST":
        department.delete()
        messages.success(request, f"Department has been deleted successfully.")
    else:
        messages.error(request, "Something went wrong.")
    return redirect("administrator:department-list")


@administrator_message
@administrator_required
def create_course_view(request, *args, **kwargs):
    context = {}
    c_form = CourseForm(request.POST or None)
    f_form = FeeForm(request.POST or None)

    if request.method == "POST":
        if c_form.is_valid() and f_form.is_valid():
            course = c_form.save()
            fee = f_form.save(commit=False)
            fee.course = course
            fee.save()
            messages.success(request, f"Course created.")
            return redirect("administrator:course-list")
        else:
            c_form = c_form
            f_form = f_form
            messages.error(request, "Error.")

    context["c_form"] = c_form
    context["f_form"] = f_form
    context["action"] = "Create"
    return render(request, "administrator/course/course_form.html", context)


@administrator_message
@administrator_required
def list_course_view(request, *args, **kwargs):
    context = {}
    courses = Course.objects.all()
    context["courses"] = courses
    return render(request, "administrator/course/course_list.html", context)


@administrator_message
@administrator_required
def detail_course_view(request, uuid, *args, **kwargs):
    context = {}
    course = get_course(uuid)
    context["course"] = course
    return render(request, "administrator/course/course_detail.html", context)


@administrator_message
@administrator_required
def update_course_view(request, uuid, *args, **kwargs):
    context = {}
    course = get_course(uuid)
    if course:
        fee = Fee.objects.get(course=course)
    c_form = CourseForm(request.POST or None, instance=course)
    f_form = FeeForm(request.POST or None, instance=fee)

    if request.method == "POST":
        if c_form.is_valid() and f_form.is_valid():
            c_form.save()
            f_form.save()
            messages.success(request, f"Course Updated.")
            return redirect("administrator:course-list")
        else:
            c_form = c_form
            f_form = f_form
            messages.error(request, "Error.")

    context["c_form"] = c_form
    context["f_form"] = f_form
    context["action"] = "Update"
    return render(request, "administrator/course/course_form.html", context)


@administrator_message
@administrator_required
def delete_course_view(request, uuid, *args, **kwargs):
    course = get_course(uuid)

    if request.method == "POST":
        course.delete()
        messages.success(request, f"Course has been deleted successfully.")
    else:
        messages.error(request, "Something went wrong.")
    return redirect("administrator:course-list")


@administrator_message
@administrator_required
def create_class_view(request, *args, **kwargs):
    context = {}
    form = ClassForm(request.POST or None)

    if request.method == "POST":
        if form.is_valid():
            form.save()
            messages.success(request, f"Class created.")
            return redirect("administrator:class-list")
        else:
            form = form
            messages.error(request, "Error.")

    context["form"] = form
    context["action"] = "Create"
    return render(request, "administrator/class/class_form.html", context)


@administrator_message
@administrator_required

administrator/templates/administrator/department/department_detail.html
{% extends 'administrator/base.html' %}
{% load static %}

{% load crispy_forms_tags %}
{% load customtags %}

{% block title %}Department Detail{% endblock title %}

{% block main %}
<div class="container">
    <div class="d-flex flex-column">
        <div class="d-flex justify-content-between my-2">
            <Legend class="m-0 fw-bold fs-3">Department Detail</Legend>
        </div>
        <table class="table mt-2">
            <thead>
                <tr></tr>
            </thead>
            <tbody>
                {% for field, value in department.get_fields_and_values %}
                <tr>
                    <td>{{field|splitFieldName|capfirst}}</td>
                    <td>{{value}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class="d-flex my-2">
            <a href="{% url 'administrator:department-update' uuid=department.id %}"
                class="btn btn-primary">Update</a>
            <button class="btn btn-danger mx-2" data-bs-toggle="modal"
                data-bs-target="#deleteDepartmentModal">delete</button>
        </div>
    </div>
</div>

<!-- Delete Department Modal -->
<div class="modal fade" id="deleteDepartmentModal" tabindex="-1" aria-labelledby="deleteModalLabel"
    aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete Department</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete this entry.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <form method="post" action="{% url 'administrator:department-delete' uuid=department.id %}">
                    {%csrf_token%}
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock main %}

administrator/templates/administrator/department/department_form.html
{% extends 'administrator/base.html' %}
{% load static %}

{% load crispy_forms_tags %}

{% block title %}{{action|capfirst}} Department{% endblock title %}

{% block main %}
<div class="container">
    <form method="post">
        <legend class="fw-bold fs-3 border-bottom">{{action|capfirst}} Department</legend>
        {% csrf_token %}
        {{form|crispy}}
        <div class="d-flex justify-content-between mt-2 pt-2 border-top">
            <button class="btn btn-primary" type="submit">{{action}}</button>
        </div>
    </form>
</div>
{% endblock main %}

administrator/templates/administrator/department/department_list.html
{% extends 'administrator/base.html' %}
{% load static %}

{% load crispy_forms_tags %}

{% block title %}Department List{% endblock title %}

{% block main %}
<div class="container">
    <div class="d-flex flex-column">
        <Legend class="m-0 fw-bold fs-3 border-bottom">Departments</Legend>
        <div class="d-flex justify-content-between my-2 pb-2 border-bottom">
            <form method="post">
                {% csrf_token %}
                <input type="text" name="search" class="form-control-sm">
                <button class="btn btn-sm btn-primary" type="submit">Search</button>
            </form>
            <div>
                <a href="{% url 'administrator:department-add' %}" class="btn btn-sm btn-primary mx-4">AddNew</a>
            </div>
        </div>
        {% if departments %}
        <table class="table table-hover table-responsive">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Code</th>
                </tr>
            </thead>
            <tbody>
                {% for object in departments %}
                <tr>
                    <td><a href="{% url 'administrator:department-detail' uuid=object.id %}">{{object.name}}</a></td>
                    <td><a href="{% url 'administrator:department-detail' uuid=object.id %}">{{object.code}}</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <div class="d-flex justify-content-center">No Records.</div>
        {% endif %}
    </div>
</div>
{% endblock main %}