administrator/urls.py
from django.urls import path

from administrator.views import (
    create_academic_session_view,
    create_assign_view,
    create_class_view,
    create_course_view,
    create_department_view,
    create_subject_view,
    create_time_slot_view,
    delete_academic_session_view,
    delete_assign_view,
    delete_class_view,
    delete_course_view,
    delete_department_view,
    delete_subject_view,
    delete_time_slot_view,
    detail_academic_session_view,
    detail_assign_view,
    detail_class_view,
    detail_course_view,
    detail_department_view,
    detail_subject_view,
    detail_time_slot_view,
    home_view,
    list_academic_session_view,
    list_assign_view,
    list_class_view,
    list_course_view,
    list_department_view,
    list_subject_view,
    list_time_slot_view,
    update_academic_session_view,
    update_assign_view,
    update_class_view,
    update_course_view,
    update_department_view,
    update_subject_view,
    update_time_slot_view,
)
from administrator.views_staff import (
    create_staff_view,
    delete_staff_view,
    detail_staff_view,
    list_staff_view,
    password_change_view,
    profile_update_view,
    profile_view,
    update_staff_view,
)
from administrator.views_student import (
    create_student_view,
    delete_student_view,
    detail_student_view,
    list_student_view,
    update_student_view,
)

app_name = "administrator"

urlpatterns = [
    path("", home_view, name="home"),
    path("academic_session_add/", create_academic_session_view, name="academic-session-add"),
    path("academic_session_list/", list_academic_session_view, name="academic-session-list"),
    path("academic_session_detail/<uuid>/", detail_academic_session_view, name="academic-session-detail"),
    path("academic_session_update/<uuid>/", update_academic_session_view, name="academic-session-update"),
    path("academic_session_delete/<uuid>/", delete_academic_session_view, name="academic-session-delete"),
    path("department_add/", create_department_view, name="department-add"),
    path("department_list/", list_department_view, name="department-list"),
    path("department_detail/<uuid>/", detail_department_view, name="department-detail"),
    path("department_update/<uuid>/", update_department_view, name="department-update"),
    path("department_delete/<uuid>/", delete_department_view, name="department-delete"),
    path("course_add/", create_course_view, name="course-add"),
    path("course_list/", list_course_view, name="course-list"),
    path("course_detail/<uuid>/", detail_course_view, name="course-detail"),
    path("course_update/<uuid>/", update_course_view, name="course-update"),
    path("course_delete/<uuid>/", delete_course_view, name="course-delete"),
    path("class_add/", create_class_view, name="class-add"),
    path("class_list/", list_class_view, name="class-list"),
    path("class_detail/<uuid>/", detail_class_view, name="class-detail"),
    path("class_update/<uuid>/", update_class_view, name="class-update"),
    path("class_delete/<uuid>/", delete_class_view, name="class-delete"),
    path("subject_add/", create_subject_view, name="subject-add"),
    path("subject_list/", list_subject_view, name="subject-list"),
    path("subject_detail/<uuid>/", detail_subject_view, name="subject-detail"),
    path("subject_update/<uuid>/", update_subject_view, name="subject-update"),
    path("subject_delete/<uuid>/", delete_subject_view, name="subject-delete"),
    path("time_slot_add/", create_time_slot_view, name="time-slot-add"),
    path("time_slot_list/", list_time_slot_view, name="time-slot-list"),
    path("time_slot_detail/<uuid>/", detail_time_slot_view, name="time-slot-detail"),
    path("time_slot_update/<uuid>/", update_time_slot_view, name="time-slot-update"),
    path("time_slot_delete/<uuid>/", delete_time_slot_view, name="time-slot-delete"),
    path("assign_add/", create_assign_view, name="assign-add"),
    path("assign_list/", list_assign_view, name="assign-list"),
    path("assign_detail/<uuid>/", detail_assign_view, name="assign-detail"),
    path("assign_update/<uuid>/", update_assign_view, name="assign-update"),
    path("assign_delete/<uuid>/", delete_assign_view, name="assign-delete"),
    # Student Views
    path("student_add/", create_student_view, name="student-add"),
    path("student_list/", list_student_view, name="student-list"),
    path("student_detail/<uuid>/", detail_student_view, name="student-detail"),
    path("student_update/<uuid>/", update_student_view, name="student-update"),
    path("student_delete/<uuid>/", delete_student_view, name="student-delete"),
    # Staff Views
    path("staff_add/", create_staff_view, name="staff-add"),
    path("staff_list/", list_staff_view, name="staff-list"),
    path("staff_detail/<uuid>/", detail_staff_view, name="staff-detail"),
    path("staff_update/<uuid>/", update_staff_view, name="staff-update"),
    path("staff_delete/<uuid>/", delete_staff_view, name="staff-delete"),
    # Profile Views
    path("profile/", profile_view, name="profile"),
    path("profile_update/", profile_update_view, name="profile-update"),
    path("password_change/", password_change_view, name="password-change"),
]

base/urls.py
from django.urls import path

from base.views import (
    email_verify_view,
    home_view,
    login_view,
    logout_view,
    password_change_view,
    password_reset_request_view,
    password_reset_view,
    register_view,
    user_deactivate_view,
    user_delete_view,
    user_profile_view,
    user_update_view,
)

app_name = "base"

urlpatterns = [
    path("", home_view, name="home"),
    path("register/", register_view, name="user-register"),
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("user_profile/", user_profile_view, name="user-profile"),
    path("user_profile/<str:user_id>", user_profile_view, name="user-profile"),
    path("user_update/", user_update_view, name="user-update"),
    path("email_verification/<uidb64>/<token>/", email_verify_view, name="email-verify"),
    path("password_change/", password_change_view, name="password-change"),
    path("password_reset_request/", password_reset_request_view, name="password-reset-request"),
    path("password_reset/<uidb64>/<token>/", password_reset_view, name="password-reset"),
    path("user_deactivate/", user_deactivate_view, name="user-deactivate"),
    path("user_delete/", user_delete_view, name="user-delete"),
]

school/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("base/", include("base.urls", namespace="base")),
    path("administrator/", include("administrator.urls", namespace="administrator")),
    path("accountant/", include("accountant.urls", namespace="accountant")),
    path("staff/", include("staff.urls", namespace="staff")),
    path("student/", include("student.urls", namespace="student")),
    path("conference/", include("conference.urls", namespace="conference")),
    path("", include("website.urls", namespace="website")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "base.views.page_not_found_view"

staff/urls.py
from django.urls import path

from staff.views import (
    home_view,
    password_change_view,
    profile_update_view,
    profile_view,
    take_attendence_view,
)

app_name = "staff"

urlpatterns = [
    path("", home_view, name="home"),
    path("take_attendence/<uuid>/", take_attendence_view, name="take-attendence"),
    # Profile Views
    path("profile/", profile_view, name="profile"),
    path("profile_update/", profile_update_view, name="profile-update"),
    path("password_change/", password_change_view, name="password-change"),
]

staff/models.py
import time
import uuid

from django.db import models
from django.utils.translation import gettext_lazy as _

from administrator.models import Assign, Student


class Attendence(models.Model):
    id = models.UUIDField(
        verbose_name=_("ID"),
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
    )
    assign = models.ForeignKey(
        Assign,
        on_delete=models.PROTECT,
    )
    student = models.ForeignKey(
        Student,
        on_delete=models.CASCADE,
    )
    date = models.DateField(
        verbose_name=_("Date"),
        auto_now_add=True,
    )
    is_present = models.BooleanField(
        default=False,
    )

    def __str__(self):
        return f"{self.student.user.name} {self.is_present}"

administrator/forms.py
from django import forms
from phonenumber_field.formfields import RegionalPhoneNumberWidget

from administrator.models import (
    AcademicSession,
    Address,
    Assign,
    Class,
    Course,
    Department,
    Staff,
    Student,
    Subject,
    TimeSlot,
)


class AcademicSessionForm(forms.ModelForm):
    class Meta:
        model = AcademicSession
        fields = "__all__"
        widgets = {
            "start_date": forms.DateInput(attrs={"type": "date"}),
            "end_date": forms.DateInput(attrs={"type": "date"}),
        }


class DepartmentForm(forms.ModelForm):
    class Meta:
        model = Department
        fields = "__all__"


class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = "__all__"


class ClassForm(forms.ModelForm):
    class Meta:
        model = Class
        fields = "__all__"


class SubjectForm(forms.ModelForm):
    class Meta:
        model = Subject
        fields = "__all__"


class TimeSlotForm(forms.ModelForm):
    class Meta:
        model = TimeSlot
        fields = "__all__"
        widgets = {
            "start_time": forms.TimeInput(attrs={"type": "time"}),
            "end_time": forms.TimeInput(attrs={"type": "time"}),
        }


class AssignForm(forms.ModelForm):
    class Meta:
        model = Assign
        fields = "__all__"


class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = "__all__"


class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = (
            "current_class",
            "gender",
            "dob",
            "fathers_name",
            "fathers_contact_no",
            "mothers_name",
            "mothers_contact_no",
            "document",
        )
        widgets = {
            "dob": forms.DateInput(attrs={"type": "date"}),
        }


class StaffForm(forms.ModelForm):
    class Meta:
        model = Staff
        fields = (
            "gender",
            "dob",
            "fathers_name",
            "document",
        )
        widgets = {
            "dob": forms.DateInput(attrs={"type": "date"}),
        }

staff/forms.py
from django import forms

from staff.models import Attendence


class AttendenceForm(forms.ModelForm):
    class Meta:
        model = Attendence
        fields = ("student", "is_present")

staff/views.py
import datetime

from django.contrib import messages
from django.forms import modelformset_factory
from django.shortcuts import redirect, render

from administrator.forms import AddressForm, StaffForm
from administrator.models import Assign, Staff, Student
from administrator.views import get_assign
from base.forms import PasswordChangeForm, UserUpdateForm
from staff.decorators import staff_message, staff_required
from staff.forms import AttendenceForm
from staff.models import Attendence

weekday = {
    0: "Monday",
    1: "Tuesday",
    2: "Wednesday",
    3: "Thursday",
    4: "Friday",
    5: "Saturday",
    6: "Sunday",
}


@staff_message
@staff_required
def home_view(request, *args, **kwargs):
    context = {}

    user = request.user
    staff = Staff.objects.filter(user=user).first()

    day_number = datetime.datetime.today().weekday()
    assigns = Assign.objects.filter(teacher=staff, day=weekday[day_number])

    context["assigns"] = assigns
    return render(request, "staff/home.html", context)


@staff_message
@staff_required
def take_attendence_view(request, uuid, *args, **kwargs):
    context = {}

    assign = get_assign(uuid=uuid)
    date = datetime.datetime.today()
    attendence_class = assign.assign_class
    students = Student.objects.filter(current_class=attendence_class)

    attendence_query_list = Attendence.objects.filter(date=date, assign=assign)
    AttendenceFormSet = modelformset_factory(Attendence, AttendenceForm, extra=0)

    if request.method == "GET":
        if attendence_query_list:
            form = AttendenceFormSet(queryset=attendence_query_list)
        else:
            for student in students:
                Attendence.objects.create(assign=assign, student=student, date=date, is_present=False)
            attendence_query_list = Attendence.objects.filter(date=date, assign=assign)
            form = AttendenceFormSet(queryset=attendence_query_list)

    if request.method == "POST":
        form = AttendenceFormSet(request.POST)
        if form.is_valid():
            form.save()
            return redirect("staff:home")
        else:
            form = form
            messages.warning(request, "Error...")

    context["form"] = form
    return render(request, "staff/take_attendence.html", context)


@staff_message
@staff_required
def profile_view(request, *args, **kwargs):
    return render(request, "staff/profile.html")


@staff_message
@staff_required
def profile_update_view(request, *args, **kwargs):
    context = {}
    user = request.user
    staff = Staff.objects.get(user=user)

    u_form = UserUpdateForm(request.POST or None, request.FILES or None, instance=staff.user)
    s_form = StaffForm(request.POST or None, request.FILES or None, instance=staff)
    pa_form = AddressForm(request.POST or None, instance=staff.permanent_address)
    ca_form = AddressForm(request.POST or None, instance=staff.current_address)

    if request.method == "POST":
        if u_form.is_valid() and s_form.is_valid() and pa_form.is_valid() and ca_form.is_valid():
            user = u_form.save()
            p_address = pa_form.save()
            c_address = ca_form.save()
            staff = s_form.save()
            staff.user = user
            staff.permanent_address = p_address
            staff.current_address = c_address
            staff.save()
            messages.success(request, f"Profile updated successfully.")
            return redirect("staff:profile")

        else:
            u_form, s_form, pa_form, ca_form = u_form, s_form, pa_form, ca_form
            messages.error(request, "Error.")

    context["u_form"] = u_form
    context["s_form"] = s_form
    context["pa_form"] = pa_form
    context["ca_form"] = ca_form
    return render(request, "staff/profile_update.html", context)


@staff_message
@staff_required
def password_change_view(request, *args, **kwargs):
    context = {}

    user = request.user
    form = PasswordChangeForm(user, request.POST or None)

    if request.method == "POST":
        if form.is_valid():
            form.save()
            messages.success(request, f"Password changed successfully. Please login with new password to continue.")
        else:
            form = form
            messages.error(request, "Error.")

    context["form"] = form
    return render(request, "staff/password_change.html", context)

administrator/templates/administrator/staff/staff_detail.html
{% extends 'administrator/base.html' %}
{% load static %}

{% load crispy_forms_tags %}
{% load customtags %}

{% block title %}Staff Detail{% endblock title %}

{% block main %}
<div class="container">
    <div class="d-flex flex-column">
        <div class="d-flex justify-content-between my-2">
            <Legend class="m-0 fw-bold fs-3">Staff Detail</Legend>
        </div>
        <table class="table mt-2">
            <thead>
                <tr></tr>
            </thead>
            <tbody>
                {% for field, value in staff.get_fields_and_values %}
                <tr>
                    <td>{{field|capfirst|removeUnderscore:"_"}}</td>
                    <td>{{value}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        <div class="d-flex justify-content-between my-2">
            <Legend class="m-0 fw-bold fs-4">User Detail</Legend>
        </div>
        <table class="table mt-2">
            <thead>
                <tr></tr>
            </thead>
            <tbody>
                {% for field, value in staff.user.get_fields_and_values %}
                <tr>
                    <td>{{field|splitFieldName|capfirst}}</td>
                    <td>{{value}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        <div class="d-flex justify-content-between my-2">
            <Legend class="m-0 fw-bold fs-4">Current Address</Legend>
        </div>
        <table class="table mt-2">
            <thead>
                <tr></tr>
            </thead>
            <tbody>
                {% for field, value in staff.current_address.get_fields_and_values %}
                <tr>
                    <td>{{field|splitFieldName|capfirst}}</td>
                    <td>{{value}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        <div class="d-flex justify-content-between my-2">
            <Legend class="m-0 fw-bold fs-4">Permanent Address</Legend>
        </div>
        <table class="table mt-2">
            <thead>
                <tr></tr>
            </thead>
            <tbody>
                {% for field, value in staff.permanent_address.get_fields_and_values %}
                <tr>
                    <td>{{field|splitFieldName|capfirst}}</td>
                    <td>{{value}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        <div class="d-flex my-2">
            <a href="{% url 'administrator:staff-update' uuid=staff.id %}" class="btn btn-primary">Update</a>
            <button class="btn btn-danger mx-2" data-bs-toggle="modal"
                data-bs-target="#deleteStaffModal">delete</button>
        </div>
    </div>
</div>

<!-- Delete Staff Modal -->
<div class="modal fade" id="deleteStaffModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete Staff</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete this entry.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <form method="post" action="{% url 'administrator:staff-delete' uuid=staff.id %}">
                    {%csrf_token%}
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock main %}

administrator/templates/administrator/staff/staff_form.html
{% extends 'administrator/base.html' %}
{% load static %}

{% load crispy_forms_tags %}

{% block title %}{{action|capfirst}} Staff{% endblock title %}

{% block main %}
<div class="container">
    <form method="post" enctype="multipart/form-data">
        <legend class="fw-bold fs-3 border-bottom">{{action|capfirst}} Staff</legend>
        {% csrf_token %}
        <p class="mt-4 fw-bold border-bottom">User Information</p>
        {{u_form|crispy}}
        <p class="mt-4 fw-bold border-bottom">General Information</p>
        {{s_form|crispy}}
        <p class="mt-4 fw-bold border-bottom">Permanent Address</p>
        {{pa_form|crispy}}
        <p class="mt-4 fw-bold border-bottom">Current Address</p>
        {{ca_form|crispy}}
        <div class="d-flex justify-content-between my-2 pt-2 border-top">
            <button class="btn btn-primary" type="submit">{{action}}</button>
        </div>
    </form>
</div>
{% endblock main %}

administrator/templates/administrator/staff/staff_list.html
{% extends 'administrator/base.html' %}
{% load static %}

{% load crispy_forms_tags %}

{% block title %}Staff List{% endblock title %}

{% block main %}
<div class="container">
    <div class="d-flex flex-column">
        <Legend class="m-0 fw-bold fs-3 border-bottom">Staffs</Legend>
        <div class="d-flex justify-content-between my-2 pb-2 border-bottom">
            <form method="post">
                {% csrf_token %}
                <input type="text" name="search" class="form-control-sm">
                <button class="btn btn-sm btn-primary" type="submit">Search</button>
            </form>
            <div>
                <a href="{% url 'administrator:staff-add' %}" class="btn btn-sm btn-primary mx-4">AddNew</a>
            </div>
        </div>
        {% if staffs %}
        <table class="table table-hover table-responsive">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Email</th>
                    <th scope="col">Contact No.</th>
                    <th scope="col">Fathers Name</th>
                </tr>
            </thead>
            <tbody>
                {% for object in staffs %}
                <tr>
                    <td><a href="{% url 'administrator:staff-detail' uuid=object.id %}">{{object.user.name}}</a></td>
                    <td><a href="{% url 'administrator:staff-detail' uuid=object.id %}">{{object.user.email}}</a></td>
                    <td><a
                            href="{% url 'administrator:staff-detail' uuid=object.id %}">{{object.user.contact_number}}</a>
                    </td>
                    <td><a href="{% url 'administrator:staff-detail' uuid=object.id %}">{{object.fathers_name}}</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <div class="d-flex justify-content-center">No Records.</div>
        {% endif %}
    </div>
</div>
{% endblock main %}