base/urls.py
from django.urls import path

from base.views import (
    email_verify_view,
    home_view,
    login_view,
    logout_view,
    password_change_view,
    password_reset_request_view,
    password_reset_view,
    register_view,
    user_deactivate_view,
    user_delete_view,
    user_profile_view,
    user_update_view,
)

app_name = "base"

urlpatterns = [
    path("", home_view, name="home"),
    path("register/", register_view, name="user-register"),
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("user_profile/", user_profile_view, name="user-profile"),
    path("user_profile/<str:user_id>", user_profile_view, name="user-profile"),
    path("user_update/", user_update_view, name="user-update"),
    path("email_verification/<uidb64>/<token>/", email_verify_view, name="email-verify"),
    path("password_change/", password_change_view, name="password-change"),
    path("password_reset_request/", password_reset_request_view, name="password-reset-request"),
    path("password_reset/<uidb64>/<token>/", password_reset_view, name="password-reset"),
    path("user_deactivate/", user_deactivate_view, name="user-deactivate"),
    path("user_delete/", user_delete_view, name="user-delete"),
]

school/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("base/", include("base.urls", namespace="base")),
    path("administrator/", include("administrator.urls", namespace="administrator")),
    path("accountant/", include("accountant.urls", namespace="accountant")),
    path("staff/", include("staff.urls", namespace="staff")),
    path("student/", include("student.urls", namespace="student")),
    path("conference/", include("conference.urls", namespace="conference")),
    path("", include("website.urls", namespace="website")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "base.views.page_not_found_view"

base/forms.py
from django import forms
from django.contrib.auth import authenticate, password_validation
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import gettext_lazy as _

from base.models import User
from base.widgets import CustomFileInput


class LoginForm(forms.Form):
    email = forms.EmailField(max_length=255, widget=forms.EmailInput)
    password = forms.CharField(max_length=255, widget=forms.PasswordInput)

    def clean_email(self):
        email = self.cleaned_data["email"]
        return email.lower()

    def is_valid(self):
        super().is_valid()
        email = self.cleaned_data["email"]
        password = self.cleaned_data["password"]
        user = authenticate(email=email, password=password)
        if user:
            return True
        return False


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(max_length=127)

    class Meta:
        model = User
        fields = ("email", "username", "user_type", "name", "contact_number", "password1", "password2")


class UserUpdateForm(forms.ModelForm):
    avatar = forms.FileField(widget=CustomFileInput)

    class Meta:
        model = User
        fields = (
            "avatar",
            "email",
            "username",
            "name",
            "contact_number",
            "user_type",
        )


class PasswordChangeForm(forms.Form):
    old_password = forms.CharField(
        label=_("Old password"),
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "current-password", "autofocus": True}),
    )
    new_password1 = forms.CharField(
        label=_("New password"),
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
    )
    new_password2 = forms.CharField(
        label=_("New password confirmation"),
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
    )

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super().__init__(*args, **kwargs)

    def clean_old_password(self):
        """
        Validate that the old_password field is correct.
        """
        old_password = self.cleaned_data["old_password"]
        if not self.user.check_password(old_password):
            raise forms.ValidationError("Incorrect current password.")
        return old_password

    def clean_new_password2(self):
        password1 = self.cleaned_data.get("new_password1")
        password2 = self.cleaned_data.get("new_password2")
        if password1 and password2:
            if password1 != password2:
                raise forms.ValidationError("The two passwords didnt match.")
        password_validation.validate_password(password2, self.user)
        return password2

    def save(self, commit=True):
        password = self.cleaned_data["new_password1"]
        self.user.set_password(password)
        if commit:
            self.user.save()
        return self.user


class PasswordResetRequestForm(forms.Form):
    email = forms.EmailField(max_length=127)

    def clean_email(self):
        email = self.cleaned_data["email"]
        try:
            user = User.objects.get(email=email)
        except User.DoesNotExist:
            user = None
        if not user:
            raise forms.ValidationError("Email not registered in our database.")


class PasswordResetForm(forms.Form):
    password1 = forms.CharField(
        label=_("New password"),
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
    )
    password2 = forms.CharField(
        label=_("New password confirmation"),
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
    )

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super().__init__(*args, **kwargs)

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2:
            if password1 != password2:
                raise forms.ValidationError("The two passwords didnt match.")
        password_validation.validate_password(password2, self.user)
        return password2

    def save(self, commit=True):
        password = self.cleaned_data["password1"]
        self.user.set_password(password)
        if commit:
            self.user.save()
        return self.user

base/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.http import Http404
from django.shortcuts import redirect, render
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode

from base.forms import (
    LoginForm,
    PasswordChangeForm,
    PasswordResetForm,
    PasswordResetRequestForm,
    RegistrationForm,
    UserUpdateForm,
)
from base.models import User
from base.tokens import account_activation_token
from school.tasks import send_password_reset_email, send_user_activation_email


def get_login_type(user):
    try:
        return user.user_type.name
    except Exception as e:
        return ""


@login_required
def home_view(request, *args, **kwargs):
    context = {}
    return render(request, "base/home.html", context)


def login_view(request, *args, **kwargs):
    context = {}

    form = LoginForm(request.POST or None)

    if request.method == "POST":
        if form.is_valid():
            email = request.POST["email"]
            password = request.POST["password"]
            user = authenticate(request, email=email, password=password)

            if not user.is_active:
                user.is_active = True

            if not user.is_email_verified:
                site = get_current_site(request)
                domain = site.domain
                if settings.CELERY_SERVER_RUNNING:
                    send_user_activation_email.delay(user.id, domain)
                else:
                    send_user_activation_email(user.id, domain)
                messages.success(
                    request,
                    f"An email with verification link is sent to your Email ID. Verify Your account before login.",
                )
                return redirect("base:home")

            login(request, user)
            messages.success(request, "Login Successfull.")
            redirect_url = request.POST.get("next", None)
            if redirect_url:
                return redirect(redirect_url)

            login_type = get_login_type(user)
            match login_type:
                case "administrator":
                    return redirect("administrator:home")
                case "accountant":
                    return redirect("accountant:home")
                case "teacher":
                    return redirect("staff:home")
                case "student":
                    return redirect("student:home")
                case other:
                    return redirect("base:home")

        else:
            messages.error(request, f"Invalid email or password.")

    context["form"] = form
    return render(request, "base/login.html", context)


def register_view(request, *args, **kwargs):
    context = {}

    user = request.user
    if user.is_authenticated:
        messages.info(request, "You are already registered.")
        return redirect("base:home")

    form = RegistrationForm(request.POST or None)

    if request.method == "POST":
        if form.is_valid():
            user = form.save()

            user.username = user.email.split("@")[0]
            user.save()

            site = get_current_site(request)
            domain = site.domain
            if settings.CELERY_SERVER_RUNNING:
                send_user_activation_email.delay(user.id, domain)
            else:
                send_user_activation_email(user.id, domain)
            messages.success(
                request,
                f"An email with verification link is sent to your Email ID. Verify Your account before login.",
            )

            return redirect("base:login")

        else:
            messages.error(request, f"Error in data validation.")

    context["form"] = form
    return render(request, "base/register.html", context)


def logout_view(request, *args, **kwargs):
    logout(request)
    messages.success(request, "Logged out successfully.")
    return redirect("base:login")


@login_required
def user_profile_view(request, *args, **kwargs):
    context = {}

    user_id = kwargs.get("user_id", None)
    if user_id:
        try:
            user = User.objects.get(id=user_id)
        except User.DoesNotExist:
            raise Http404("User not found.")
    else:
        user = request.user

    context["user"] = user
    return render(request, "base/user-profile.html", context)


@login_required
def user_update_view(request, *args, **kwargs):
    context = {}

    user = request.user
    if request.method == "GET":
        form = UserUpdateForm(instance=user)

    if request.method == "POST":
        form = UserUpdateForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            return redirect("base:user-profile")
        else:
            messages.error(request, f"Error...")

    context["form"] = form
    return render(request, "base/user-update.html", context)


@login_required
def user_deactivate_view(request, *args, **kwargs):
    user = request.user

    if request.method == "POST":
        user.is_active = False
        logout(request)
        messages.success(request, f"Your account has been deactivated. Login anytime to reactivate it.")
    else:
        messages.error(request, "Something went wrong.")
    return redirect("base:home")


@login_required
def user_delete_view(request, *args, **kwargs):
    user = request.user

    if request.method == "POST":
        user.delete()
        messages.success(request, f"Your account has been deleted successfully.")
    else:
        messages.error(request, "Something went wrong.")
    return redirect("base:home")


def email_verify_view(request, uidb64, token, *args, **kwargs):
    try:
        user_id = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(id=user_id)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.is_email_verified = True
        user.save()
        login(request, user)
        messages.success(request, f"An account for {user.username} created successfully.")
        return redirect("base:home")
    else:
        messages.error(request, f"Something went wrong.")
        return redirect("base:home")


@login_required
def password_change_view(request, *args, **kwargs):
    context = {}

    user = request.user
    form = PasswordChangeForm(user, request.POST or None)

    if request.method == "POST":
        if form.is_valid():
            form.save()
            messages.success(
                request,
                f"Password changed successfully. Please login with new password to continue.",
            )
        else:
            form = form
            messages.error(request, "Error.")

    context["form"] = form
    context["header"] = "Change Password"
    context["button_text"] = "Change"
    return render(request, "base/password/password-form.html", context)


def password_reset_request_view(request, *args, **kwargs):
    context = {}

    form = PasswordResetRequestForm(request.POST or None)

    if request.method == "POST":
        if form.is_valid():
            email = request.POST["email"]

            site = get_current_site(request)
            domain = site.domain
            if settings.CELERY_SERVER_RUNNING:
                send_password_reset_email.delay(email, domain)
            else:
                send_password_reset_email(email, domain)
            messages.success(
                request,
                f"An email with password reset link is sent to your Email ID. Verify Your account before login.",
            )

        else:
            form = form
            messages.error(request, "Error.")

    context["form"] = form
    context["header"] = "Request Password Reset"
    context["button_text"] = "Request"
    return render(request, "base/password/password-form.html", context)


def password_reset_view(request, uidb64, token, *args, **kwargs):
    try:
        user_id = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(id=user_id)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    context = {}

    if user is not None and account_activation_token.check_token(user, token):
        form = PasswordResetForm(user, request.POST or None)

        if request.method == "POST":
            if form.is_valid():
                form.save()
                messages.success(
                    request,
                    f"Your password has been reset. Please login to continue.",
                )
                return redirect("base:login")
            else:
                form = form
            messages.error(request, "Error.")

        context["form"] = form
        context["header"] = "Request Password Reset"
        context["button_text"] = "Change"
        return render(request, "base/password/password-form.html", context)
    else:
        messages.info(request, f"Something went wrong.")
        return redirect("base:home")


def page_not_found_view(request, *args, **kwargs):
    return render(request, "base/page-not-found.html")

base/templates/base/base.html
{% extends 'base-template.html' %}
{% load static %}

{% block title %}{% endblock title %}

{% block body %}

{% include 'base/snippets/sidebar.html' %}
<div class="container-base">
    {% include 'base/snippets/header.html' %}
    {% include 'base/snippets/messages.html' %}
    
    <div class="container-main">
        {% block main %} {% endblock main %}
    </div>

    {% include 'base/snippets/footer.html' %}
</div>

<script>
    let sidebar = document.getElementsByClassName("sidebar")[0]

    let sidebarSize = localStorage.getItem("sidebar-size")
    if (!sidebarSize) {
        sidebarSize = "sidebar-large"
        localStorage.setItem("sidebar-size", "sidebar-large")
    }
    sidebar.classList.add(sidebarSize)

    let sidebarToggler = document.getElementById("id-sidebar-toggler")
    sidebarToggler.addEventListener("click", function () {
        sidebar.classList.toggle("sidebar-large")
        sidebar.classList.toggle("sidebar-small")
        toggleSidebarSize()
    })
    
    function toggleSidebarSize() {
        let sidebarSize = localStorage.getItem("sidebar-size")
        if (sidebarSize === "sidebar-large") {
            sidebarSize = "sidebar-small"
        } else if (sidebarSize === "sidebar-small") {
            sidebarSize = "sidebar-large"
        }
        localStorage.setItem("sidebar-size", sidebarSize)
    } 
</script>
{% endblock body %}

base/templates/base/home.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}Home{% endblock title %}

{% block main %}
<div class="container">
    <p>Home Page</p>
</div>
{% endblock main %}

base/templates/base/login.html
{% extends 'base/base.html' %}
{% load static %}

{% load crispy_forms_tags %}

{% block title %}Login{% endblock title %}

{% block main %}
<div class="container">
    <form method="post">
        <legend class="border-bottom">Login</legend>
        {% csrf_token %}
        {{form|crispy}}
        <input type="hidden" name="next" value="{{request.GET.next}}">
        <div class="d-flex justify-content-between mt-2 pt-2 border-top">
            <button class="btn btn-primary" type="submit">Login</button>
            <a class="btn" href="{% url 'base:password-reset-request' %}">Forget Password</a>
        </div>
    </form>
</div>
{% endblock main %}

base/templates/base/page_not_found.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Page not found</title>
</head>
<body>
    <div class="d-flex justify-content-center mt-4">Page Not Found</div>
</body>
</html>

base/templates/base/register.html
{% extends 'base/base.html' %}
{% load static %}

{% load crispy_forms_tags %}

{% block title %}Register{% endblock title %}

{% block main %}
<div class="container">
    <form method="post">
        <legend class="border-bottom">Register New User</legend>
        {% csrf_token %}
        {{form|crispy}}
        <div class="mt-2 pt-2 border-top">
            <button class="btn btn-primary" type="submit">Add User</button>
        </div>
    </form>
</div>
{% endblock main %}

base/templates/base/user-profile.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}Profile{% endblock title %}

{% block main %}
<div class="container">
    <div class="">
        <div class="d-flex justify-content-center">
            <img class="border rounded-circle" src="{{ user.avatar.url }}">
        </div>
        <table class="table table-responsive border-bottom mt-4">
            <tbody>
                <tr>
                    <td>Email :</td>
                    <td>{{ user.email }}</td>
                </tr>
                <tr>
                    <td>Username :</td>
                    <td>{{ user.username }}</td>
                </tr>
                <tr>
                    <td>Full Name :</td>
                    <td>{{ user.name }}</td>
                </tr>
                <tr>
                    <td>Contact No. :</td>
                    <td>{{ user.contact_number }}</td>
                </tr>
                <tr>
                    <td>User Type :</td>
                    <td>{{ user.user_type }}</td>
                </tr>
            </tbody>
        </table>
        {% if request.user == user %}
        <div class="mt-2">
            <a href="{% url 'base:user-update' %}" class="btn btn-primary mt-2">Update</a>
            <a href="{% url 'base:password-change' %}" class="btn btn-primary mt-2">Change Password</a>
            <button class="btn btn-primary mt-2" data-bs-toggle="modal" data-bs-target="#deactivateUserModal">Deactivate</button>
            <button class="btn btn-danger mt-2" data-bs-toggle="modal" data-bs-target="#deleteUserModal">Delete</button>
        </div>
        {% endif %}
    </div>
</div>

<!-- Deactivate Account Modal -->
<div class="modal fade" id="deactivateUserModal" tabindex="-1" aria-labelledby="deactivateModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deactivateModalLabel">Deactivate Account</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to deactivate your account.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <form method="post" action="{% url 'base:user-deactivate' %}" class="modal-form">
                    {%csrf_token%}
                    <button type="submit" class="btn btn-primary">Deactivate</button>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Delete Account Modal -->
<div class="modal fade" id="deleteUserModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Deactivate Account</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete your account.</p>
                <p>You will not be able to recover your account once it is deleted.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <form method="post" action="{% url 'base:user-delete' %}" class="modal-form">
                    {%csrf_token%}
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock main %}

base/templates/base/user-update.html
{% extends 'base/base.html' %}
{% load static %}

{% load crispy_forms_tags %}

{% block title %}Update User{% endblock title %}

{% block main %}
<div class="container">
    <form method="post" enctype="multipart/form-data">
        <legend class="border-bottom">Update Profile</legend>
        {% csrf_token %}
        {{form|crispy}}
        <div class="mt-2 pt-2 border-top">
            <button class="btn btn-primary" type="submit">Update</button>
        </div>
    </form>
</div>
{% endblock main %}